
{
  "DFSP_NAME": "${DFSP_NAME}",
  "DFSP_CURRENCY": "${DFSP_CURRENCY}",
  "DFSP_MSISDN": "${DFSP_MSISDN}",
  "DFSP_BUSINESS_ID": "${DFSP_BUSINESS_ID}",
  "DFSP_NOTIFICATION_EMAIL": "${DFSP_NOTIFICATION_EMAIL}"
}
