{
 "title": "Mojaloop - Central-Ledger",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Current OP/s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transfers Prepares / sec",
   "type": "singlestat",
   "description": "Transfers Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[120s]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfer Positions / sec",
   "type": "singlestat",
   "description": "Transfer Positions / sec",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_transfer_position_count{serviceName=\"central-handler-position\"}[120s]))"
    }
   ]
  },
  {
   "title": "Transfers Fullfills / sec",
   "type": "singlestat",
   "description": "Transfers Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[120s]))"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Central Ledger Lag by Consumer Group",
   "type": "graph",
   "description": "Central Ledger Lag by Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"cl-group-.*\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Central-Service - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moja_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[120s])) by (app_kubernetes_io_name, success)",
     "legendFormat": "{{app_kubernetes_io_name}} - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_transfer_position_count{serviceName=\"central-handler-position\"}[120s])) by (app_kubernetes_io_name, action, success)",
     "legendFormat": "{{app_kubernetes_io_name}} - {{action}} - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_transfer_position_count{serviceName=\"central-handler-position\"}[120s])) by (app_kubernetes_io_name, success)",
     "legendFormat": "{{app_kubernetes_io_name}}  Avg - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[120s])) by (app_kubernetes_io_name, success)",
     "legendFormat": "{{app_kubernetes_io_name}} - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[120s])) by (kubernetes_pod_name, success)",
     "legendFormat": "{{kubernetes_pod_name}} - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[120s])) by (kubernetes_pod_name, success)",
     "legendFormat": "{{kubernetes_pod_name}} - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_transfer_position_count{serviceName=\"central-handler-position\"}[120s])) by (kubernetes_pod_name, success)",
     "legendFormat": "{{kubernetes_pod_name}} - success:{{success}}"
    }
   ]
  },
  {
   "title": "Central-Service - Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moja_transfer_prepare_sum{serviceName=\"central-handler-prepare\"}[30s]) / irate(moja_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[30s])) by (success)",
     "legendFormat": "Transfer Prepare - Average - success:{{success}}"
    },
    {
     "expr": "avg(irate(moja_transfer_position_sum{serviceName=\"central-handler-position\"}[30s]) / irate(moja_transfer_position_count{serviceName=\"central-handler-position\"}[30s])) by (success)",
     "legendFormat": "Transfer Position - Average - success:{{success}}"
    },
    {
     "expr": "avg(irate(moja_transfer_fulfil_sum{serviceName=\"central-handler-fulfil\"}[30s]) / irate(moja_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[30s])) by (success)",
     "legendFormat": "Transfer Fulfil - Average - success:{{success}}"
    },
    {
     "expr": "avg(irate(moja_transfer_prepare_sum{serviceName=\"central-handler-prepare\"}[30s]) / irate(moja_transfer_prepare_count{serviceName=\"central-handler-prepare\"}[30s])) by (kubernetes_pod_name, success)",
     "legendFormat": "Transfer Prepare - {{kubernetes_pod_name}} - success:{{success}}"
    },
    {
     "expr": "avg(irate(moja_transfer_position_sum{serviceName=\"central-handler-position\"}[30s]) / irate(moja_transfer_position_count{serviceName=\"central-handler-position\"}[30s]) ) by (kubernetes_pod_name, success)",
     "legendFormat": "Transfer Position - {{kubernetes_pod_name}} - success:{{success}}"
    },
    {
     "expr": "avg(irate(moja_transfer_fulfil_sum{serviceName=\"central-handler-fulfil\"}[30s]) / irate(moja_transfer_fulfil_count{serviceName=\"central-handler-fulfil\"}[30s])) by (kubernetes_pod_name, success)",
     "legendFormat": "Transfer Fulfil - {{kubernetes_pod_name}} - success:{{success}}"
    }
   ]
  },
  {
   "title": "CPU Usage by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Central Services Total CPU Usage",
     "type": "singlestat",
     "description": "Central Services Total CPU Usage",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger.*'}[2m]))"
      }
     ]
    },
    {
     "title": "Transfer Prepare Handler CPU Usage",
     "type": "singlestat",
     "description": "Transfer Prepare Handler CPU Usage",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 26 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-prepare.*'}[2m]))"
      }
     ]
    },
    {
     "title": "Transfer Position Handler CPU Usage",
     "type": "singlestat",
     "description": "Transfer Position Handler CPU Usage",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-position.*'}[2m]))"
      }
     ]
    },
    {
     "title": "Transfer Fulfil Handler CPU Usage",
     "type": "singlestat",
     "description": "Transfer Fulfil Handler CPU Usage",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 26 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-fulfil.*'}[2m]))"
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage by Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Central Services - Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "moja_nodejs_heap_size_total_bytes{serviceName=~\"central-handler.*\"}",
     "legendFormat": "heap_total-{{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_nodejs_heap_size_used_bytes{serviceName=~\"central-handler.*\"}",
     "legendFormat": "heap_used-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Central-Service  - CPU Usage in Seconds by Pod",
   "type": "graph",
   "description": "Central-Service  - CPU Usage in Seconds by Pod",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(moja_process_cpu_seconds_total{serviceName=~\"central.*\"}[30s]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Central-Service  - Event Loop Lag in Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_nodejs_eventloop_lag_seconds{serviceName=~\"central.*\"}) by (serviceName)",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Central-Service - # Pods for each Components",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-centralledger-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}