{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(moja_nodejs_version_info, instance)"
   },
   {
    "name": "serviceName",
    "label": "serviceName",
    "query": "label_values(moja_nodejs_version_info, serviceName)"
   },
   {
    "name": "podName",
    "label": "podName",
    "query": "label_values(moja_nodejs_version_info, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(moja_process_cpu_user_seconds_total{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}[2m]) * 100",
     "legendFormat": "User CPU - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "moja_process_resident_memory_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Process Memory - {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_nodejs_heap_size_total_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Heap Total - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "moja_nodejs_eventloop_lag_seconds{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "moja_nodejs_active_handles_total{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Active Handler - {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_nodejs_active_requests_total{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Active Request - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(moja_nodejs_version_info{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(moja_process_start_time_seconds{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "moja_nodejs_heap_space_size_total_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Heap Total - {{kubernetes_pod_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "moja_nodejs_heap_space_size_used_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Heap Used - {{kubernetes_pod_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "moja_nodejs_heap_space_size_available_bytes{instance=~\"$instance\", kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}",
     "legendFormat": "Heap Used - {{kubernetes_pod_name}} - {{space}}"
    }
   ]
  }
 ]
}